Kiyonaga issue673
kurusugawa-computer/annofab-cli pull request #696
Opened 2022-02-05 01:04 UTC by pfe171

下書き

2022-02-07 03:00 UTC, yuji38kwmt commented
>API(put_annotation)を用いて、プロパティを変更をリクエストする。attributeを変更する場合と異なり、APIの仕様上annotation_idやis_protectedが必須項目になっていることから、アノテーションごとに処理する必要があるため、アノテーションの数だけリクエストを送信している。

こんな感じで処理すれば、アノテーションごとに`put_annotation`リクエストを投げる必要はないかと思います。いかがでしょうか？

```
service.api.get_editor_annotation()
annotation, _ = self.service.api.get_editor_annotation(...)

# is_protectedなどを変更したnew_detailsを
change_properties(annotation["details"])


self.service.api.put_annotation(..., request_body=annotation)
```

2022-02-07 03:12 UTC, yuji38kwmt commented
>（SingleAnnotation型の中にすでに情報はあるが、is_protectedが含まれていなかったため）

すみません、ここの意味が分からなかったです。

2022-02-07 03:12 UTC, yuji38kwmt commented on annofabcli/annotation/change_annotation_properties.py
> +    )
`change_attributes`コマンドで一時的に追加したオプションなので、`change_properties`コマンドでは不要です。削除していただきたいです。

2022-02-11 01:43 UTC, pfe171 commented
> > （SingleAnnotation型の中にすでに情報はあるが、is_protectedが含まれていなかったため）
> 
> すみません、ここの意味が分からなかったです。

申し訳ありません。言葉足らずでした。
AnnotationDetail型の`is_protected`以外の情報（`annotation_id`や`url`など）は`annotation_list`の中にすでに情報が存在しているのですが、今回は`is_protected`を変更したいとのことなのでAPI(`get_editor_annotation`)を用いて`is_protected`も含めたアノテーション情報を取得する必要がある、という意図でした。
（あまり本筋には関係ないので無視してくださった構いません）

2022-02-11 06:45 UTC, pfe171 commented
> こんな感じで処理すれば、アノテーションごとに`put_annotation`リクエストを投げる必要はないかと思います。いかがでしょうか？

自分自身、アノテーションまわりの構造について理解が足りておらず、よくわからない実装と説明をしていました。すみません。
川松さんのおっしゃる通り、アノテーションごとにリクエストを送る必要はないですね。
改めて整理して考えたところ、アノテーションごとに処理していたことにより元の実装は不具合だらけだったことが分かったため、修正しました。

不具合があった点：
- アノテーションごとに処理していたため、同じ入力データに対して複数のアノテーションがあった場合に、プロパティを変更したアノテーション以外のアノテーションが消失してしまっていた。
- 同じ入力データに対して複数のアノテーションのプロパティを変更した場合、変更が反映されていないアノテーションが出てしまっていた。

修正後：
- 入力データごとに処理するように変更しました。
- 修正後のプロパティ変更手順は以下のようになっています。
1. まず、`annotation_list`を入力データごとに整理する。
2. `get_editor_annotation`APIで、入力データに対するアノテーション情報を取得する。
3. 取得したアノテーション情報のプロパティを変更する。

2022-02-11 09:30 UTC, yuji38kwmt commented on annofabcli/annotation/change_annotation_properties.py
> +                print(annotation["details"])
print文を削除
```suggestion
```

2022-02-11 09:30 UTC, yuji38kwmt commented on annofabcli/annotation/change_annotation_properties.py
> +                            annotations["details"][idx]["is_protected"] = properties.is_protected
```suggestion
                            single_annotation["is_protected"] = properties.is_protected
```

こうすれば変数`idx`が不要になり、`enumuerate`を使わなくてよくなります。

2022-02-11 09:49 UTC, yuji38kwmt requested changes

2022-02-11 09:49 UTC, yuji38kwmt commented on annofabcli/annotation/change_annotation_properties.py
> +        required=True,
タスク内のすべてのアノテーションに対して、`is_pretected:true`を設定したいときがあるので、オプショナル引数にして欲しいです。
すみません、伝え忘れていました。


```suggestion
        required=False,
```

またオプショナル引数にしたことで、型ヒントなどの修正も必要になります。こちらも修正をお願いしたいです。

2022-02-13 00:28 UTC, pfe171 commented on annofabcli/annotation/change_annotation_properties.py
> +                            annotations["details"][idx]["is_protected"] = properties.is_protected
for文で渡される変数が値渡しだと思い込んでいました。参照渡しなのですね。覚えておきます。
ご指摘の通り修正しました。

2022-02-15 02:13 UTC, merged