タスクのステータスを作業中から休憩中にするコマンドの作成
kurusugawa-computer/annofab-cli pull request #835
Opened 2022-08-01 04:25 UTC by pfe171

**解決されるissue**
[#776](https://github.com/kurusugawa-computer/annofab-cli/issues/776)

**目的**
複数のタスクを作業中から休憩中に変更するコマンドを作る。

**実装**
change_operator.pyを参考に、issueの方で説明いただいた方針で実装しました。
ドキュメントも作成しました。

**実行コマンド**
`annofabcli task change_status_to_break --project_id PROJECT_ID --task_id TASK_ID [TASK_ID ...] [-tq TASK_QUERY] [--parallelism PARALLELISM]
`

2022-08-02 08:44 UTC, yuji38kwmt commented on annofabcli/task/change_status_to_break.py
> +class ChangeStatusToBreakMain(AbstractCommandLineWithConfirmInterface):
`AbstractCommandLineWithConfirmInterface`クラスを継承して、`confirm_processing`メソッドを宣言しなくてよいようにしました。

2022-08-02 08:46 UTC, yuji38kwmt commented
すみません、「保留中」タスクも、「休憩中」状態に変更できるようにしていただきたいです。
保留中タスクを休憩中にするには、一度作業中状態にしなくてはいけなかった気がします（未確認）

私の要件漏れです。失礼いたしました。

2022-08-02 23:57 UTC, pfe171 commented on annofabcli/task/change_status_to_break.py
> +class ChangeStatusToBreakMain(AbstractCommandLineWithConfirmInterface):
こちらの方が簡潔ですね。修正ありがとうございます。

2022-08-03 00:47 UTC, yuji38kwmt requested changes

2022-08-03 00:47 UTC, yuji38kwmt commented on annofabcli/task/change_status_to_break.py
> +    parser = annofabcli.common.cli.add_parser(subparsers, subcommand_name, subcommand_help, description, epilog=epilog)
```suggestion
    epilog = "アノテータ、チェッカーまたはオーナロールを持つユーザで実行してください。"
```

アノテータロールも実行できるので、追記

2022-08-03 00:47 UTC, yuji38kwmt commented on annofabcli/task/change_status_to_break.py
> +        super().validate_project(project_id, [ProjectMemberRole.OWNER, ProjectMemberRole.ACCEPTER])
```suggestion
        super().validate_project(project_id, [ProjectMemberRole.OWNER, ProjectMemberRole.ACCEPTER, ProjectMemberRole.WORKER])
```

2022-08-03 01:47 UTC, merged